spring.application.name=inventory-service
server.port=8085

# MongoDB
spring.mongodb.uri=mongodb://carolusbrisky:<password>@ac-hrpawkh-shard-00-02.vxqntlx.mongodb.net:27017/inventorydb?ssl=true&authSource=admin&directConnection=true&appName=Cluster0

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Retry 3x
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0

logging.level.com.example.inventory_service=DEBUG